name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    container: rust:alpine
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        apk update
        apk add npm
        npm install --global nushell
    - name: Build
      run: cargo build --all-features --all-targets --workspace
    - name: Run formatter
      run: cargo fmt -- --check
    - name: Run linter
      run: cargo clippy --all-features --all-targets --workspace
    - name: Run tests
      run: cargo test --all-features --all-targets --workspace
